### ISSUE TITLE
los-14.1 tree

### ISSUE THREAD

**Issue by Kandykun** [dianlujitao/android_device_xiaomi_jason#1]
Hi dianlujitao

Could you please push any of your cm-14.1/lineage-14.1/mk1-mr1 branches? Specifically the one used to build: https://androidfilehost.com/?fid=817550096634801439. 
I would like to build it from your tree.

Thanks,
Kandykun

**Comment by moetayuko** [comment]
I'll release the source code in the future, but definitely not now.
